stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Default
      demands:
      - agent.name -equals Weltgeist
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"

 